YaLTeR/bxt-rs

- src/hooks/engine.rs
Turns out that the pattern from the 4554 engine matches for two functions on the 1600 build, and I couldn't immediately notice it.
> engine: extend 4554 pattern for Cmd_AddMallocCommand

- src/modules/capture/mod.rs
It was overflowing because of the bugged gauss charge sound in the Steam version.
> capture: Use wrapping multiplication for sample pairs

- bxt-strafe/src/lib.rs
- bxt-strafe/src/steps.rs
- src/modules/tas_optimizer/mod.rs
- src/modules/tas_optimizer/simulator.rs
Hmmm, it doesn't look up to standard from my standard.
> CS1.6 related changes for TAS Optimizer

- src/hooks/sdl.rs
On parity with BunnymodXT to allow game to run in full performance in background, aka InActive.
> Force SDL_WaitEventTimeout to 0 on bxt-rs side

- src/modules/demo_playback.rs
"wildcard" is not really wildcard as it won't attempt to match things like what it should, more meant for folder.
`enumerate()` pretty much does nothing but I think it is better to keep it there to log something for the tuple.
> Add bxt_play_folder

- src/hooks/engine.rs
- src/modules/capture/mod.rs
- src/modules/capture_video_per_demo.rs
- src/modules/mod.rs
Closes #56
~~Still WIP but it works~~. There are some details worth discussing and a bug looking bit too much to fix.
Right now, it couples with "bxt_play_run/folder" and it will ignore "bxt_cap_start" argument. Not sure what the argument should mean but in the mentioned issue, I propose to have it as the prefix for the file name ("prefix_demoname.mp4" as a result). But that route needs #57 to be properly addressed. Otherwise, I think the argument could mean THE file name and following split will have number trailing ("filename_number.mp4"). That is what I can come up with to still have "bxt_cap_start" around. 
If we go with the prefix, the demo name of the first demo seems a bit too much to get. I look around the source and getting the demo file name is really tricky. `demo_playback.rs` …
> capture: Add bxt_cap_start_segment

- src/utils/pointer.rs
> Rust 1.70 new pointer dereference alignment debug

- src/hooks/engine.rs
- src/modules/mod.rs
- src/modules/viewmodel_remove.rs
- src/modules/viewmodel_sway.rs
~~Naming might be subjected to changes depending on uncool factors.~~
Name is changed. Only 6% less cool.
> Add viewmodel sway

- src/modules/tas_studio/mod.rs
More explanation.
In Bunnnymodxt, HwDLL.cpp, this snippet is executed.
In bxt-rs playback hook `bxt_tas_load_script_from_string`, that part is not included.
The important part here is setting active mouse.
> studio: fix CS 1.6 unfocused playback

- src/hooks/engine.rs
- src/modules/fix_widescreen.rs
- src/modules/mod.rs
Port of https://github.com/YaLTeR/BunnymodXT/pull/448 with fix from https://github.com/YaLTeR/BunnymodXT/issues/451
I was thinking of doing the fix differently by restoring `scr_fov_value` after some functions are done using it (biggestly `R_RenderView`).
That might be or might be not necessary. Because this is a "fix", so it should not really write some info into the demo, I thought to myself. But I guess this would be just fine.
> Port bxt_fix_widescreen_fov

- src/hooks/engine.rs
- src/modules/capture_skip_non_gameplay.rs
- src/modules/mod.rs
Recording normally would have loading. Here is a recording with lots of segments.
https://user-images.githubusercontent.com/29143195/202879114-02ab1feb-d821-4f17-b2c9-b077560f6acc.mp4
Here is one without loading. 
https://user-images.githubusercontent.com/29143195/202879124-a0059725-377b-4829-bdb7-0496491e3741.mp4
The `frame_count` could be changed around to omit early frames entirely. Though it might come at a cost of recording become janky. Some frames are broken as #2 mentions. That would need something else.
> capture: Add _bxt_cap_skip_non_gameplay_frames

- src/hooks/engine.rs
- src/modules/lightstyle.rs
- src/modules/mod.rs
aka night vision
No need for mat_fullbright 1 and -75% fps if use this one instead. No need for tweaking gamma and brightness either. Most importantly, no need to restart the map.
> Add bxt_lightstyle

- src/modules/lightstyle.rs
This weird wiki error has been out a while and mildy irritating some people. Anyways, I have to bounce.
> Oh! See thee OCD's odyssey. Ought dc.
> Fix bxt_lightstyle wiki

- src/hooks/bxt.rs
- src/modules/tas_studio/editor/mod.rs
- src/modules/tas_studio/mod.rs
Closes #96 
I think the organizing is a bit weird. Not sure how to go around that because this needs the game itself to work.
Need https://github.com/YaLTeR/BunnymodXT/pull/520 to have it work.
> Add camera view editing mode

- bxt-strafe/src/lib.rs
- src/hooks/bxt.rs
- src/hooks/engine.rs
- src/modules/tas_studio/editor/mod.rs
- src/modules/tas_studio/mod.rs
Closes #97 
Intended to work with yaw (and pitch) override and also without.
Seems pretty okay.
I don't want to figure out how to keep the same position after replay but if it is needed then I shall.
If no second game and no tas playback first time then viewangles replay won't work (not a problem and no one would encounter it but can be fixed very easy or not depending on the simulated run would override the values or not).
And
> bxt_tas_norefresh_until_last_frames = 0 means 1 frame being played. Heh.
If that needs changing then sure. I don't want to complicate all of the logic too much.
> Add bxt_tas_studio_replay_views

- Cargo.toml
- bxt-ipc-types/Cargo.toml
- bxt-strafe/Cargo.toml
- bxt-strafe/src/lib.rs
- bxt-strafe/src/steps.rs
- src/hooks/bxt.rs
- src/modules/tas_optimizer/optimizer.rs
- src/modules/tas_optimizer/simulator.rs
- src/modules/tas_studio/editor/mod.rs
- src/modules/tas_studio/editor/operation.rs
- src/modules/tas_studio/editor/utils.rs
- src/modules/tas_studio/mod.rs
Needs hltas update.
There are some things about this. First, I want that when a frame bulk of this type is split, it shouldn't reset the acceleration values. That is why the weird gymnastics is here. 
Second, I want it a bit easier to use so there's text popping up like #100 . I think it is pretty okay. I don't think the console command for this would be that necessary. 
No third point but I don't want to pass "accurate" data, specifically the current accumulated yawspeed, from BXT to bxt-rs because I think bxt-strafe won't ever mess it up.
I play around with it for a bit and it is very confusing to use. Might get some time getting used to because you have two parameters. I put some thoughts into the interactions and I think it works great for me. Not sure about others.
> Add Max Acceleration Yaw Offset

- src/hooks/engine.rs
- src/modules/emit_sound.rs
- src/modules/mod.rs
Edit: S_StartDynamicSound might be not what I want. It doesn't work per channel as I thought it would. The reason why I changed to S_StartDynamicSound is to avoid doing extra precache mechanism so any sounds can be played. I think I might need to revert two recent changes and then figure out how to do precache (or maybe not).
Edit 2: Never mind, it is good. I am just hallucinating.
Edit 3: After some more playing around, I think I have to make it similar to `speak` where it emits from where the player view is, rather than player origin. Big TODO in there and I thought it wouldn't come back.
Final edit: This should be good. I learn that the issue I've been having is just misusing the attenuation value. So now there are two options to emit sound with two different commands. Though for …
> Add bxt_emit_sound

- src/hooks/engine.rs
- src/modules/mod.rs
- src/modules/show_player_in_hltv.rs
closes #117 
The implementation is very similar to BXT. I also realize that I have been taking this feature for granted, recording a few demos with this feature without knowing it is a feature.
There is `Cmd_FindCmd` but I just feel like it is easier to just implement my own.
> add show_player_in_hltv

- src/modules/campath/mod.rs
To create a campath file inside Blender, there must be a map file in Blender. Usually, people use "Nem's Crafty" to export GoldSrc BSP into OBJ. However, Crafty is for Source. GoldSrc 90 degrees yaw is Source 0 degrees yaw or something. 
If people were to have the source file of the map, which is JMF or MAP, and they export that inside Blender, the OBJ has correct orientation for GoldSrc. And when exporting a campath created based on that source map file, HLAE Blender Plugins can mess up the rotation. The result is the campath and rotation look right in Blender, but not in the game.
After rotating the points with basic math, need to change the viewangles as well.
> campath: add option to rotate camera points around origin Z axis

- .cargo/config.toml
Lots of big repos have this fix so I guess it is a okay.
> fix debug build linker error on github ci windows-2022
